import React, { useState, useEffect } from 'react';
import { Sun, UploadCloud, Activity, Mic, Video, Link as LinkIcon, Download, Sparkles, ArrowRight, ChevronDown, CheckCircle, Image as ImageIcon, FileText, Shield, ShoppingCart, BookOpen, Palette, Users } from 'lucide-react';
import { BrowserRouter, Routes, Route, useNavigate, Navigate, Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import Navbar from './Navbar';
import AuthLayout from './AuthLayout';
import Login from './Login';
import Signup from './Signup';
import AudioDetection from './AudioDetection';
import VideoDetection from './VideoDetection';
import AudioProcessing from './AudioProcessing';
import VideoProcessing from './VideoProcessing';
import Features from './Features';
import Contact from './Contact';

const handleSmoothScroll = (e, targetId) => {
  e.preventDefault();
  
  if (window.location.pathname !== '/hero' && window.location.pathname !== '/') {
    window.location.href = `/hero${targetId}`;
    return;
  }
  
  const targetElement = document.querySelector(targetId);
  if (!targetElement) return;

  const targetPosition = targetElement.getBoundingClientRect().top + window.scrollY - 80;
  const startPosition = window.scrollY;
  const distance = targetPosition - startPosition;
  const duration = 1200;
  let start = null;

  const easing = (t) => t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;

  const animation = (currentTime) => {
    if (start === null) start = currentTime;
    const timeElapsed = currentTime - start;
    const progress = Math.min(timeElapsed / duration, 1);
    
    window.scrollTo(0, startPosition + distance * easing(progress));
    
    if (timeElapsed < duration) {
      requestAnimationFrame(animation);
    } else {
      window.history.pushState(null, '', targetId);
    }
  };

  requestAnimationFrame(animation);
};

function ScrollReveal({ children, delay = 0 }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1], delay }}
    >
      {children}
    </motion.div>
  );
}

function Dashboard() {
  const [openFAQ, setOpenFAQ] = React.useState(null);
  
  return (
    <div className="min-h-screen bg-[#FBFBFC] font-sans text-[#1a1a1a] flex flex-col">
      {/* ─── NAVBAR ───────────────────────────────────────── */}
      <Navbar />

      {/* ─── HERO IMAGE ────────────────────────────────────────────────────── */}
      <div 
        className="w-full h-[55vh] max-h-[600px] border-b border-gray-200"
        style={{
          backgroundImage: "url('/runcycle-bg.jpg')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat'
        }}
      ></div>
      {/* ─── GENERATORS MARQUEE ────────────────────────────────────────────── */}
      <div className="w-full bg-[#FAFAFA] py-16 border-b border-gray-200 overflow-hidden flex flex-col items-center justify-center">
        <div className="max-w-[1000px] text-center px-6 mb-12">
           <h2 className="text-[32px] font-bold text-[#1a1a1a] mb-4 tracking-tight">Works Across Popular AI Image Generators</h2>
           <p className="text-[16px] text-gray-500 font-medium">
             The AI Image Detector identifies images generated by all popular AI models including Midjourney, DALL-E 3, Stable Diffusion, Ideogram, Google DeepMind, Leonardo.Ai, Adobe Firefly, Canva, Runway, and Flux.
           </p>
        </div>
        
        <div className="w-full relative flex items-center group">
           <style>{`
             @keyframes marquee {
               0% { transform: translateX(0%); }
               100% { transform: translateX(-50%); }
             }
             .animate-marquee {
               display: flex;
               width: max-content;
               animation: marquee 85s linear infinite;
             }
           `}</style>
           
           <div className="absolute left-0 top-0 w-32 h-full bg-gradient-to-r from-[#FAFAFA] to-transparent z-10 pointer-events-none"></div>
           <div className="absolute right-0 top-0 w-32 h-full bg-gradient-to-l from-[#FAFAFA] to-transparent z-10 pointer-events-none"></div>

           <div className="animate-marquee flex gap-16 md:gap-24 items-center px-8 py-4">
             {[...Array(4)].map((_, i) => (
               <React.Fragment key={i}>
                 <img src="/logo4.png" alt="Ideogram" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0" />
                 <img src="/logo7.png" alt="Runway" className="h-12 md:h-14 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0" />
                 <img src="/logo2.png" alt="DeepMind" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0" />
                 <img src="/logo1.png" alt="Midjourney" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0 mix-blend-multiply contrast-125 brightness-110" />
                 <img src="/logo8.png" alt="Canva" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0 mix-blend-multiply contrast-125 brightness-110" />
                 <img src="/logo6.png" alt="Flux" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0" />
                 <img src="/logo3.png" alt="Stable Diffusion" className="h-16 md:h-20 w-auto object-contain hover:scale-105 transition-all cursor-pointer shrink-0" />
                 <img src="/logo5.png" alt="DALL-E 3" className="h-20 md:h-24 w-auto object-contain hover:scale-110 transition-all cursor-pointer shrink-0 mix-blend-multiply contrast-[1.1] brightness-[1.05]" />
                 <img src="/logo9.png" alt="Adobe Firefly" className="h-40 md:h-56 lg:h-64 w-auto object-contain hover:scale-110 transition-all cursor-pointer shrink-0" />
                 <img src="/logo10.png" alt="Leonardo.Ai" className="h-20 md:h-24 w-auto object-contain hover:scale-110 transition-all cursor-pointer shrink-0" />
               </React.Fragment>
             ))}
           </div>
        </div>
      </div>

      {/* ─── CONTENT SECTION ───────────────────────────────────────────────── */}
      <div className="w-full bg-[#FBFBFC] py-16 flex justify-center px-8">
        <div className="max-w-[1500px] w-full relative rounded-2xl overflow-hidden bg-[#050505] shadow-2xl border border-gray-900">
          
          {/* Background Image restricted to right side */}
          <div 
            className="absolute right-0 top-0 bottom-0 w-full lg:w-[70%]"
            style={{
              backgroundImage: "url('/hero-bg-2.png')",
              backgroundSize: 'cover',
              backgroundPosition: 'center right',
              backgroundRepeat: 'no-repeat'
            }}
          ></div>
          
          {/* Gradient to ensure smooth blend from the solid black left side into the image */}
          <div className="absolute inset-0 bg-gradient-to-r from-[#050505] via-[#050505]/95 to-transparent w-full lg:w-[65%] pointer-events-none"></div>

          <div className="relative z-10 w-full px-10 md:px-16 py-24 min-h-[550px] flex flex-col justify-center">
            {/* Left: Heading and button */}
            <div className="lg:w-[55%]">
              <div className="text-[#4274F6] font-mono text-[13px] font-bold tracking-[0.2em] uppercase mb-5">
                Advanced Forensics
              </div>
              
              <h1 className="text-[40px] md:text-[48px] lg:text-[56px] leading-[1.1] font-['Playfair_Display'] font-bold tracking-tight text-white mb-6 drop-shadow-md">
                AI agent that takes<br/>all your media forensics
              </h1>
              
              <p className="text-[16px] md:text-[18px] text-gray-300 mb-12 leading-relaxed max-w-[90%]">
                State-of-the-art models built to detect the invisible — analyzing images, audio, and video — to combat digital deception and uncover the absolute truth behind synthetic media.
              </p>
              
              <div className="flex flex-wrap items-center gap-8">
                {/* Button */}
                <Link to="/video-detection" className="group relative inline-flex items-center justify-center p-1 rounded-full bg-white/10 backdrop-blur-md border border-white/20 hover:scale-105 transition-transform duration-300 cursor-pointer w-max">
                  <div className="flex items-center gap-3 bg-[#4274F6] text-white pl-2 pr-5 py-2 rounded-full shadow-[0_10px_30px_-10px_rgba(66,116,246,0.6)]">
                    <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center group-hover:bg-gray-50 transition-colors">
                      <ArrowRight className="w-5 h-5 text-[#4274F6] group-hover:translate-x-1 transition-transform" />
                    </div>
                    <span className="text-[17px] font-bold tracking-tight">Start Detection</span>
                  </div>
                </Link>

                {/* Secondary Link */}
                <a href="#how-to-use" onClick={(e) => handleSmoothScroll(e, '#how-to-use')} className="bg-white text-black px-7 py-3 rounded-full font-bold text-[16px] flex items-center justify-center hover:bg-black hover:text-white transition-colors duration-300 shadow-sm border border-transparent hover:border-gray-700">
                  How to Use
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ─── HOW TO USE ────────────────────────────────────────────────────── */}
      <ScrollReveal>
      <div id="how-to-use" className="max-w-[1500px] mx-auto px-8 pt-24 pb-8 flex flex-col lg:flex-row gap-16 items-center bg-[#FBFBFC] scroll-mt-24">
        <div className="lg:w-1/2">
          <h2 className="text-[36px] font-bold text-[#1a1a1a] mb-4">How to Use Deepfake Image Detection</h2>
          <p className="text-[16px] text-gray-500 mb-10 leading-relaxed">
            It's super easy. Just upload a photo, let our AI Deepfake Image Detection do the work, and get a full report in seconds. You'll see what's real, what's not—and why. No tech skills needed. No sign-up. No stress.
          </p>
          
          <div className="space-y-8">
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <UploadCloud className="w-5 h-5 text-blue-600" /> Step 1: Upload Your Image
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">Click the upload button and select any photo you want to check. You can drag and drop too. We support JPG, PNG, and even some edited screenshots.</p>
            </div>
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <Activity className="w-5 h-5 text-blue-600" /> Step 2: Detect Image
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">Once uploaded, our AI Deepfake Image Detection gets to work fast. It scans for clues like lighting, shadows, pixel noise, and face textures.</p>
            </div>
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <CheckCircle className="w-5 h-5 text-blue-600" /> Step 3: Review the Detection Report
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">In just a few seconds, you'll see a summary showing the authenticity score—how likely the image is real or fake. We also give you a detailed report.</p>
            </div>
          </div>
          
          <div className="mt-10">
            <Link to="/video-detection" className="group relative inline-flex items-center justify-center p-1.5 rounded-full bg-blue-100/50 backdrop-blur-md border border-blue-200/50 hover:scale-105 transition-transform duration-300 cursor-pointer w-max mt-2">
              <div className="flex items-center gap-4 bg-[#4274F6] text-white pl-7 pr-2 py-2 rounded-full shadow-[0_10px_30px_-10px_rgba(66,116,246,0.6)]">
                <span className="text-[17px] font-bold tracking-tight">Try Deepfake Image & Video Detection</span>
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center group-hover:translate-x-1 transition-transform">
                  <ArrowRight className="w-5 h-5 text-[#4274F6]" />
                </div>
              </div>
            </Link>
          </div>
        </div>
        
        <div className="lg:w-1/2">
           {/* Mockup visual */}
           <div className="w-full bg-white rounded-2xl p-6 border border-gray-100 shadow-2xl relative">
              <div className="w-full h-48 bg-gray-50 border-2 border-dashed border-gray-200 rounded-xl mb-4 flex items-center justify-center">
                 <div className="text-center">
                   <UploadCloud className="w-10 h-10 text-gray-300 mx-auto mb-2" />
                   <p className="text-sm font-medium text-gray-400">Drag & drop an image</p>
                 </div>
              </div>
              <div className="flex gap-4">
                 <div className="w-1/2 h-32 bg-gray-50 border border-gray-200 rounded-xl relative overflow-hidden flex items-center justify-center">
                    <ImageIcon className="w-10 h-10 text-gray-400" />
                 </div>
                 <div className="w-1/2 h-32 bg-gray-50 border border-gray-200 rounded-xl p-4 flex flex-col justify-center">
                    <div className="h-3 w-1/2 bg-gray-200 rounded-full mb-2"></div>
                    <div className="h-3 w-3/4 bg-gray-200 rounded-full mb-4"></div>
                    <div className="h-8 w-full bg-red-50 text-red-600 font-bold text-xs flex items-center justify-center rounded-lg border border-red-100">FAKE (87%)</div>
                 </div>
              </div>
           </div>
        </div>
      </div>
      </ScrollReveal>
      {/* ─── HOW TO USE (AUDIO) ────────────────────────────────────────────── */}
      <ScrollReveal>
      <div className="max-w-[1500px] mx-auto px-8 pt-8 pb-24 flex flex-col lg:flex-row-reverse gap-16 items-center bg-[#FBFBFC]">
        <div className="lg:w-1/2">
          <h2 className="text-[36px] font-bold text-[#1a1a1a] mb-4">How to Use Deepfake Audio Detection</h2>
          <p className="text-[16px] text-gray-500 mb-10 leading-relaxed">
            It's super easy. Just upload an audio file, let our AI Deepfake Audio Detection do the work, and get a full report in seconds. You'll see what's real, what's not—and why. No tech skills needed. No sign-up. No stress.
          </p>
          
          <div className="space-y-8">
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <UploadCloud className="w-5 h-5 text-purple-600" /> Step 1: Upload Your Audio
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">Click the upload button and select any audio file you want to check. You can drag and drop too. We support MP3, WAV, and even some extracted video audio.</p>
            </div>
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <Activity className="w-5 h-5 text-purple-600" /> Step 2: Detect Audio
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">Once uploaded, our AI Deepfake Audio Detection gets to work fast. It scans for clues like synthetic frequencies, breathing patterns, voice cloning artifacts, and unnatural pacing.</p>
            </div>
            <div>
              <h3 className="text-[18px] font-bold text-[#1a1a1a] flex items-center gap-2 mb-2">
                <CheckCircle className="w-5 h-5 text-purple-600" /> Step 3: Review the Detection Report
              </h3>
              <p className="text-[15px] text-gray-500 pl-7 leading-relaxed">In just a few seconds, you'll see a summary showing the authenticity score—how likely the audio is real or cloned. We also give you a detailed report.</p>
            </div>
          </div>
          
          <div className="mt-10">
            <Link to="/audio-detection" className="group relative inline-flex items-center justify-center p-1.5 rounded-full bg-blue-100/50 backdrop-blur-md border border-blue-200/50 hover:scale-105 transition-transform duration-300 cursor-pointer w-max mt-2">
              <div className="flex items-center gap-4 bg-[#4274F6] text-white pl-7 pr-2 py-2 rounded-full shadow-[0_10px_30px_-10px_rgba(66,116,246,0.6)]">
                <span className="text-[17px] font-bold tracking-tight">Try Deepfake Audio Detection</span>
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center group-hover:translate-x-1 transition-transform">
                  <ArrowRight className="w-5 h-5 text-[#4274F6]" />
                </div>
              </div>
            </Link>
          </div>
        </div>
        
        <div className="lg:w-1/2">
           {/* Mockup visual */}
           <div className="w-full bg-white rounded-2xl p-6 border border-gray-100 shadow-2xl relative">
              <div className="w-full h-48 bg-gray-50 border-2 border-dashed border-gray-200 rounded-xl mb-4 flex items-center justify-center">
                 <div className="text-center">
                   <UploadCloud className="w-10 h-10 text-gray-300 mx-auto mb-2" />
                   <p className="text-sm font-medium text-gray-400">Drag & drop an audio file</p>
                 </div>
              </div>
              <div className="flex gap-4">
                 <div className="w-1/2 h-32 bg-gray-50 border border-gray-200 rounded-xl relative overflow-hidden flex items-center justify-center">
                    <Mic className="w-10 h-10 text-gray-400" />
                 </div>
                 <div className="w-1/2 h-32 bg-gray-50 border border-gray-200 rounded-xl p-4 flex flex-col justify-center">
                    <div className="h-3 w-1/2 bg-gray-200 rounded-full mb-2"></div>
                    <div className="h-3 w-3/4 bg-gray-200 rounded-full mb-4"></div>
                    <div className="h-8 w-full bg-red-50 text-red-600 font-bold text-xs flex items-center justify-center rounded-lg border border-red-100">CLONED (92%)</div>
                 </div>
              </div>
           </div>
        </div>
      </div>
      </ScrollReveal>

      {/* ─── WHO CAN BENEFIT ───────────────────────────────────────────────── */}
      <ScrollReveal>
      <div className="w-full bg-white py-24 border-y border-gray-100">
        <div className="max-w-[1500px] mx-auto px-8">
          <h2 className="text-[36px] font-bold text-center mb-16 text-[#1a1a1a]">Who Can Benefit from AI Image Detection</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-12 gap-y-16 text-center">
            
            {/* Item 1 */}
            <div className="flex flex-col items-center">
              <img src="/benefit1.png" alt="Journalists" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">Journalists & Newsrooms</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Verify the AI-based source of images in newsworthy events. Ensure credibility and accuracy in reporting by detecting manipulated or AI-generated visuals before publication.
              </p>
            </div>

            {/* Item 2 */}
            <div className="flex flex-col items-center">
              <img src="/benefit2.png" alt="Online Platforms" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">Online Platforms & Moderation Teams</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Equip AI image checker to ensure platform integrity and user trust. Automatically detect and flag potentially misleading AI-generated content before it goes viral on social media.
              </p>
            </div>

            {/* Item 3 */}
            <div className="flex flex-col items-center">
              <img src="/benefit3.png" alt="E-Commerce" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">E-Commerce & Marketplaces</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Help prevent deceptive product listings by identifying AI generated or manipulated product images. Maintain marketplace integrity and protect consumers from misleading visual content.
              </p>
            </div>

            {/* Item 4 */}
            <div className="flex flex-col items-center">
              <img src="/benefit4.png" alt="Researchers" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">Researchers & Educators</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Study the impact of AI-generated imagery and teach media literacy. Equip students with critical thinking skills to evaluate the authenticity of digital content.
              </p>
            </div>

            {/* Item 5 */}
            <div className="flex flex-col items-center">
              <img src="/benefit5.png" alt="Designers" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">Designers & Artists</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Be a part of creative AI-image communities while protecting originality and attribution. Ensure transparency when AI assistance is used in creative workflows.
              </p>
            </div>

            {/* Item 6 */}
            <div className="flex flex-col items-center">
              <img src="/benefit6.png" alt="General Users" className="w-24 h-24 mb-6 object-contain hover:scale-105 transition-transform cursor-pointer" />
              <h3 className="text-[18px] font-bold text-[#1a1a1a] mb-3">General Users</h3>
              <p className="text-[14px] text-gray-500 leading-relaxed">
                Develop AI media literacy and protect yourself from disinformation. Learn to identify when images have been AI-generated or manipulated before sharing.
              </p>
            </div>

          </div>
        </div>
      </div>
      </ScrollReveal>
      {/* ─── TECHNOLOGY ────────────────────────────────────────────────────── */}
      {/* ─── TECHNOLOGY ────────────────────────────────────────────────────── */}
      <ScrollReveal>
      <div id="technology" className="w-full bg-white py-20 border-b border-gray-100 scroll-mt-24">
        <div className="max-w-[1400px] mx-auto px-8">
          <div className="mb-12">
            <h2 className="text-[14px] font-bold text-gray-500 uppercase tracking-widest mb-2">Core Technology</h2>
            <h3 className="text-[36px] font-bold text-black leading-tight">Engineered for Forensic Precision.</h3>
            <p className="text-[16px] text-gray-600 mt-4 max-w-2xl">
              Schrödinger utilizes a state-of-the-art dual-modal pipeline combining Vision Transformers, EfficientNet, and Mel-Spectrogram networks to detect microscopic synthetic anomalies.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
            <div>
              <h4 className="text-[20px] font-bold text-black mb-6">The Detection Pipeline</h4>
              <ul className="space-y-6">
                <li>
                  <h5 className="text-[16px] font-bold text-black">1. Extraction & Alignment</h5>
                  <p className="text-[15px] text-gray-600 mt-1">Videos are processed frame-by-frame using MTCNN and Azure Computer Vision. Faces are detected, tightly cropped, and geometrically aligned to ensure the model focuses purely on facial manipulation artifacts without background interference.</p>
                </li>
                <li>
                  <h5 className="text-[16px] font-bold text-black">2. Spatial Feature Extraction</h5>
                  <p className="text-[15px] text-gray-600 mt-1">The aligned 128×128 pixel inputs are fed into our customized EfficientNet backbone. This deep architecture extracts high-level spatial features, detecting microscopic inconsistencies in blending, lighting, and pixel textures.</p>
                </li>
                <li>
                  <h5 className="text-[16px] font-bold text-black">3. Classification & Scoring</h5>
                  <p className="text-[15px] text-gray-600 mt-1">Extracted spatial features are passed through dense fully connected layers equipped with dropout regularization. The final Sigmoid activation yields a definitive probability score.</p>
                </li>
              </ul>
            </div>

            <div className="bg-[#FAFAFA] p-8 border border-gray-200 rounded-[16px]">
              <h4 className="text-[20px] font-bold text-black mb-6">Model Performance</h4>
              <div className="flex gap-8 mb-8">
                <div>
                  <p className="text-[12px] text-gray-500 font-bold uppercase mb-1">Accuracy</p>
                  <p className="text-[32px] font-bold text-black leading-none">96.3%</p>
                </div>
                <div>
                  <p className="text-[12px] text-gray-500 font-bold uppercase mb-1">Precision</p>
                  <p className="text-[32px] font-bold text-black leading-none">94.9%</p>
                </div>
                <div>
                  <p className="text-[12px] text-gray-500 font-bold uppercase mb-1">Recall</p>
                  <p className="text-[32px] font-bold text-black leading-none">97.9%</p>
                </div>
              </div>
              <p className="text-[14px] text-gray-600 mb-6">Outperforms XceptionNet & MesoNet on the FaceForensics++ benchmark.</p>
              
              {/* Real System Graph */}
              <div className="w-full bg-white rounded-lg overflow-hidden border border-gray-200">
                 <img src="/benchmark.png" alt="System Benchmark Graph" className="w-full h-auto object-cover" />
              </div>
            </div>
          </div>
        </div>
      </div>
      </ScrollReveal>

      {/* ─── DEVELOPERS ────────────────────────────────────────────────────── */}
      <ScrollReveal>
      <div id="developers" className="w-full py-32 scroll-mt-24 relative bg-[url('/noise-bg.png')] bg-cover bg-center">
        <div className="max-w-[1200px] mx-auto px-8 relative z-10 flex flex-col justify-between min-h-[900px]">
          
          {/* Top Section - Light background area -> Dark text */}
          <div className="text-center mb-16 pt-10">
            <h2 className="text-[14px] font-bold text-gray-500 uppercase tracking-widest mb-3">Developers</h2>
            <h3 className="text-[42px] font-bold mb-4 text-[#1a1a1a] leading-tight">Train a deepfake detection model from scratch.</h3>
            <p className="text-[18px] text-gray-600 mb-2">Full pipeline, scripts, and documentation on GitHub.</p>
            <p className="text-[13px] text-gray-500 font-medium mt-6">Developed by <span className="text-[#1a1a1a] font-bold">Yuvan Vishnu Pandi, Siva Surya M, Naveen Karthik</span></p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 flex-grow mb-16">
            {/* Left Column -> Frosted White Glass Card */}
            <div className="bg-white/40 backdrop-blur-xl p-10 rounded-[24px] border border-white/50 shadow-[0_8px_32px_rgba(0,0,0,0.05)]">
              <p className="text-[16px] text-gray-800 leading-relaxed mb-8">
                The Schrödinger repository guides you through building a deep learning–based deepfake detector using Python, Keras, and TensorFlow. The model uses a customized EfficientNet backbone (128×128 input, binary classifier for deepfake vs. pristine) and is trained on a large set of public deepfake datasets so you can run inference, fine-tune, or train from scratch on your own data.
              </p>
              
              <h4 className="text-[20px] font-bold mb-4 text-[#1a1a1a]">Pipeline</h4>
              <p className="text-[15px] text-gray-700 leading-relaxed mb-8">
                The repo includes scripts for: converting video frames to images, face extraction (MTCNN or Azure Computer Vision API), dataset balancing and train/val/test split, and CNN training. Prerequisites: Python 3, Keras, TensorFlow, OpenCV, MTCNN. MIT License.
              </p>
              
              <a href="https://github.com/aaronchong888/DeepFake-Detect" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#1a1a1a] text-white px-7 py-3.5 rounded-full font-bold text-[14px] hover:bg-black transition-all shadow-lg mt-2 hover:scale-105">
                View repository on GitHub
              </a>
            </div>
            
            {/* Right Column -> Frosted Dark Glass Card */}
            <div className="bg-black/40 backdrop-blur-xl p-10 rounded-[24px] border border-black/20 shadow-[0_8px_32px_rgba(0,0,0,0.3)]">
              <h4 className="text-[20px] font-bold mb-4 text-white">Training datasets</h4>
              <p className="text-[15px] text-gray-300 leading-relaxed mb-6">
                The sample models are trained on 134,000+ videos across ~1,140 identities and ~20 synthesis methods. Supported datasets include:
              </p>
              <ul className="space-y-5 text-[14px] font-medium">
                <li><a href="https://www.idiap.ch/dataset/deepfaketimit" target="_blank" rel="noreferrer" className="text-gray-100 hover:text-white transition-colors flex items-center gap-3"><div className="w-1.5 h-1.5 bg-white rounded-full"></div>DeepFake-TIMIT</a></li>
                <li><a href="https://github.com/ondyari/FaceForensics" target="_blank" rel="noreferrer" className="text-gray-100 hover:text-white transition-colors flex items-center gap-3"><div className="w-1.5 h-1.5 bg-white rounded-full"></div>FaceForensics++</a></li>
                <li><a href="https://ai.googleblog.com/2019/09/contributing-data-to-deepfake-detection.html" target="_blank" rel="noreferrer" className="text-gray-100 hover:text-white transition-colors flex items-center gap-3"><div className="w-1.5 h-1.5 bg-white rounded-full"></div>Google Deep Fake Detection (DFD)</a></li>
                <li><a href="https://github.com/danmohaha/celeb-deepfakeforensics" target="_blank" rel="noreferrer" className="text-gray-100 hover:text-white transition-colors flex items-center gap-3"><div className="w-1.5 h-1.5 bg-white rounded-full"></div>Celeb-DF</a></li>
                <li><a href="https://ai.facebook.com/datasets/dfdc/" target="_blank" rel="noreferrer" className="text-gray-100 hover:text-white transition-colors flex items-center gap-3"><div className="w-1.5 h-1.5 bg-white rounded-full"></div>Facebook Deepfake Detection Challenge</a></li>
              </ul>
            </div>
          </div>
          
          {/* Bottom Section - Dark background area -> Light text */}
          <div className="text-center pb-4 pt-12 border-t border-gray-600/30">
            <p className="text-[16px] text-gray-300 font-medium tracking-wide">Schrödinger — deepfake detection for the web and for researchers. Train, deploy, verify.</p>
          </div>
        </div>
      </div>
      </ScrollReveal>

      {/* ─── FAQ ───────────────────────────────────────────────────────────── */}
      <ScrollReveal delay={0.1}>
      <div id="faq" className="max-w-[1500px] mx-auto px-8 py-20 pb-32 scroll-mt-24">
        <h2 className="text-[32px] font-bold text-center mb-12">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {[
            { 
              q: "What is deepfake image detection?", 
              a: "Deepfake image detection is an advanced, AI-powered forensic process that rigorously analyzes an image's pixel structure, metadata, and lighting inconsistencies. By passing the media through multiple deep learning layers, our engine can determine with high precision if an image was synthetically generated by tools like Midjourney, DALL-E, or manipulated via complex deep learning networks like GANs." 
            },
            { 
              q: "Is the deepfake detector 100% accurate?", 
              a: "While our models achieve state-of-the-art detection rates exceeding 98% on major AI generators, no forensic tool is mathematically 100% accurate. We always recommend using our detailed explainability reports to fully understand the confidence score, the highlighted artifacts, and the overall context of every single forensic analysis we provide." 
            },
            { 
              q: "Is my data safe?", 
              a: "Absolutely. Privacy and security are our foundational pillars. We employ strict, zero-retention policies across all servers. Your uploaded media is encrypted in transit using bank-grade protocols, processed entirely in isolated memory environments, and permanently, irreversibly purged from our servers the exact moment your forensic report is generated." 
            },
            { 
              q: "What file types does the product support?", 
              a: "We currently support a wide array of standard industry formats. For images, we support JPG, PNG, WEBP, and TIFF. For audio forensics, you can upload MP3 and WAV files. For our advanced temporal video analysis, we currently process MP4 and MOV formats up to 4K resolution." 
            },
            { 
              q: "How do I interpret the detection results?", 
              a: "Upon analysis, you will receive a clear, easily understandable percentage score indicating the exact likelihood of synthetic generation. Beyond just a score, the report dynamically highlights specific forensic anomalies—such as unnatural blending boundaries, synthetic noise patterns, or biological impossibilities like asymmetrical pupil reflections—directly on the media." 
            },
            { 
              q: "How to handle false positives?", 
              a: "If you suspect a false positive, we urge you to review the 'Explainability Report' which breaks down exactly why the AI flagged the media. It is important to note that very heavy, manual digital alterations—such as extreme Instagram beauty filters, heavy retouching, or aggressive JPEG compression artifacts—can sometimes trigger our forensic alerts due to their synthetic nature." 
            },
            { 
              q: "How does the product adapt to evolving deepfake technology?", 
              a: "The generative AI landscape moves incredibly fast. To counter this, our forensic models are aggressively retrained on a weekly basis. We utilize adversarial networks and actively collect massive, proprietary datasets from the absolute latest generative models (like Flux, DALL-E 3, and Sora) to ensure we always stay one step ahead of emerging manipulation techniques." 
            },
            { 
              q: "Is there a free version or trial?", 
              a: "Yes! You can use our basic detection tools completely for free, subject to a daily rate limit to prevent abuse. For large-scale moderation teams, journalists, and enterprise API access requiring bulk processing, we offer highly scalable premium tiers that come with a comprehensive 14-day free trial." 
            },
            { 
              q: "How can I integrate it into my workflow?", 
              a: "We provide a highly robust REST API, a dedicated Python SDK, and direct plug-and-play integrations for common platforms. This comprehensive developer suite allows moderation teams, newsrooms, and platforms to automatically flag and quarantine synthetic content directly within their existing CMS, Slack channels, or moderation dashboards." 
            }
          ].map((faq, i) => (
            <div 
              key={i} 
              className={`bg-white border ${openFAQ === i ? 'border-[#4274F6] shadow-md' : 'border-gray-200 shadow-sm'} rounded-xl overflow-hidden transition-all duration-300`}
            >
               <div 
                 className="p-6 cursor-pointer flex justify-between items-center bg-white"
                 onClick={() => setOpenFAQ(openFAQ === i ? null : i)}
               >
                 <span className={`font-bold text-[16px] ${openFAQ === i ? 'text-[#4274F6]' : 'text-[#1a1a1a]'}`}>{faq.q}</span>
                 <ChevronDown className={`w-5 h-5 transition-transform duration-300 ${openFAQ === i ? 'rotate-180 text-[#4274F6]' : 'text-gray-400'}`} />
               </div>
               
               <div 
                 className={`px-6 transition-all duration-500 ease-in-out ${openFAQ === i ? 'max-h-[500px] opacity-100 pb-6' : 'max-h-0 opacity-0'}`}
               >
                 <div className="w-full h-px bg-gray-100 mb-4"></div>
                 <p className="text-gray-600 leading-relaxed text-[15px]">
                   {faq.a}
                 </p>
               </div>
            </div>
          ))}
        </div>
      </div>
      </ScrollReveal>

      {/* ─── FOOTER ────────────────────────────────────────────────────────── */}
      <footer className="w-full bg-gradient-to-b from-[#e3ecf9] to-[#b3ccf2] pt-20 overflow-hidden mt-auto">
        <div className="max-w-[1400px] mx-auto px-12 relative z-10 flex flex-col md:flex-row justify-between items-start mb-24">
          
          <div className="md:w-1/3 flex flex-col gap-5 text-[15px] font-bold text-[#1a1a1a]">
             <a href="https://arxiv.org/abs/2008.12262" target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-blue-600 transition-colors group">
               <div className="w-10 h-10 rounded-full border border-gray-300 flex items-center justify-center group-hover:border-blue-600 group-hover:bg-white transition-colors shadow-sm">
                 <span className="font-serif font-bold text-[12px] tracking-tighter text-gray-600 group-hover:text-blue-600">arXiv</span>
               </div>
               Attention-based Deepfake Detection
             </a>
             <a href="https://ieeexplore.ieee.org/document/8630761" target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-blue-600 transition-colors group">
               <div className="w-10 h-10 rounded-full border border-gray-300 flex items-center justify-center group-hover:border-blue-600 group-hover:bg-white transition-colors shadow-sm">
                 <span className="font-sans font-black text-[10px] tracking-widest text-gray-600 group-hover:text-blue-600">IEEE</span>
               </div>
               Exposing Face Warping Artifacts
             </a>
             <a href="https://www.sciencedirect.com/science/article/pii/S104732032030113X" target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-blue-600 transition-colors group">
               <div className="w-10 h-10 rounded-full border border-gray-300 flex items-center justify-center bg-white group-hover:border-blue-600 transition-colors shadow-sm overflow-hidden p-1">
                 <img src="/sciencedirect-logo.png" alt="ScienceDirect" className="w-full h-full object-contain" />
               </div>
               Deep Learning for Deepfakes
             </a>
          </div>
          
          <div className="md:w-1/3 flex justify-center items-center">
             <a href="https://github.com/your-repo" target="_blank" rel="noreferrer" className="bg-white text-black px-8 py-3.5 rounded-full font-bold text-[16px] flex items-center justify-center hover:bg-black hover:text-white transition-colors duration-300 shadow-sm">
               View Repository
             </a>
          </div>
          
          <div className="md:w-1/3 flex flex-col items-end gap-3 text-[15px] font-bold text-[#1a1a1a]">
             <a href="#" className="hover:text-blue-600 transition-colors">Tools</a>
             <a href="#" className="hover:text-blue-600 transition-colors">Technology</a>
             <a href="#" className="hover:text-blue-600 transition-colors">Developers</a>
             <a href="#" className="hover:text-blue-600 transition-colors">FAQ</a>
          </div>
        </div>

        <div className="flex justify-center items-center px-12 mb-8 text-[12px] font-bold text-gray-500 relative z-10">
          <span>© 2026 Schrödinger. All Rights Reserved</span>
        </div>

        {/* Big Background Text */}
        <div className="w-full flex justify-center pointer-events-none opacity-[0.15] translate-y-[20%]">
          <h1 className="text-[18vw] leading-none font-bold text-center tracking-tighter text-blue-900 m-0 p-0" style={{ letterSpacing: '-0.05em' }}>
            schrödinger
          </h1>
        </div>
      </footer>
    </div>
  );
}

function LoginWrapper() {
  const navigate = useNavigate();
  return <Login onLogin={() => navigate('/')} />;
}

function SignupWrapper() {
  const navigate = useNavigate();
  return <Signup onSignup={() => navigate('/')} />;
}

const pageVariants = {
  initial: { opacity: 0, y: 15, filter: 'blur(4px)' },
  animate: { opacity: 1, y: 0, filter: 'blur(0px)', transition: { duration: 0.3, ease: [0.22, 1, 0.36, 1] } },
  exit: { opacity: 0, y: -15, filter: 'blur(4px)', transition: { duration: 0.2, ease: [0.22, 1, 0.36, 1] } }
};

function PageWrapper({ children }) {
  return (
    <motion.div initial="initial" animate="animate" exit="exit" variants={pageVariants} className="w-full h-full">
      {children}
    </motion.div>
  );
}

function ScrollToTop() {
  const { pathname } = useLocation();
  
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);
  
  return null;
}

function AnimatedRoutes() {
  const location = useLocation();
  return (
    <>
      <ScrollToTop />
      <AnimatePresence mode="wait">
        <Routes location={location} key={location.pathname}>
          <Route path="/" element={<Navigate to="/hero" replace />} />
          <Route path="/hero" element={<PageWrapper><Dashboard /></PageWrapper>} />
          <Route path="/audio-detection" element={<PageWrapper><AudioDetection /></PageWrapper>} />
          <Route path="/audio-processing" element={<PageWrapper><AudioProcessing /></PageWrapper>} />
          <Route path="/video-detection" element={<PageWrapper><VideoDetection /></PageWrapper>} />
          <Route path="/video-processing" element={<PageWrapper><VideoProcessing /></PageWrapper>} />
          <Route path="/features" element={<PageWrapper><Features /></PageWrapper>} />
          <Route path="/contact" element={<PageWrapper><Contact /></PageWrapper>} />
          <Route element={<AuthLayout />}>
            <Route path="/login" element={<PageWrapper><LoginWrapper /></PageWrapper>} />
            <Route path="/signup" element={<PageWrapper><SignupWrapper /></PageWrapper>} />
          </Route>
        </Routes>
      </AnimatePresence>
    </>
  );
}

export default function App() {
  return (
    <BrowserRouter>
      <AnimatedRoutes />
    </BrowserRouter>
  );
}